version: '2'
services:
  database:
    image: postgres:9.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "p0stgr@s"
      POSTGRES_DB:       "stockdb"
  stockservice:
    container_name: stock-service
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    image: skayvanfar/stock-service:stocking
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      SERVER_PORT: "8080"
      DATABASESERVER_PORT: "5432"
    depends_on:
      - database
