version: '3.9'
services:
  postgresql-db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "stock"
      POSTGRES_PASSWORD: "SToc1K"
      POSTGRES_DB:       "stockdb"
  stockservice:
    container_name: stock-service
    build:
      context: ../../
      dockerfile: docker/Dockerfile
    image: skayvanfar/stock-service:stocking
    ports:
      - "8080:8080"
    environment:
      PROFILE: "default"
      STOCK_DB_URL: 'jdbc:postgresql://postgresql-db:5432/stockdb'
      STOCK_DB_USER: 'stock'
      STOCK_DB_PASSWORD: 'SToc1K'
      SERVER_PORT: "8080"
      DATABASESERVER_PORT: "5432"
    depends_on:
      - postgresql-db
