spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://database:5432/stockdb"
    username: "postgres"
    password: "p0stgr@s"
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

#Setting the logging levels for the service
logging:
  level:
    com.netflix: WARN
    org.springframework.web: WARN
    ir.sk.eagleeye: DEBUG
    ir.sk.microservice: DEBUG