server:
  port: ${API_PORT:8080}
#  servlet:
#    context-path: /stock-service
spring:
  application:
    name: stock-service
  profiles:
    active:
      ${PROFILE:default}
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    url: ${STOCK_DB_URL:jdbc:postgresql://localhost:5432/stockdb}
    username: ${STOCK_DB_USER:stock}
    password: ${STOCK_DB_PASSWORD:SToc1K}
    hikari:
      maximum-pool-size: 15
      auto-commit: false
      max-lifetime: 600000
      keepalive-time: 300000
      data-source-properties:
        reWriteBatchedInserts: true
        tcpKeepAlive: true
        ipTypes: PUBLIC,PRIVATE
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true

#Setting the logging levels for the service
logging:
  level:
    org.springframework.web: WARN
    ir.sk.stock: DEBUG
