spring:
  datasource:
    driverClassName: org.h2.Driver
    password: ''
    url: jdbc:h2:mem:stockdb
    username: sa
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    dialect: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        format_sql: true
        validator:
          apply_to_ddl: false
    show-sql: true
    defer-datasource-initialization: true