version:  '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres_prod"
      POSTGRES_PASSWORD:  "p0stgr@s_prod"
      POSTGRES_DB: "stockdb_prod"
  stockservice:
    image: skayvanfar/stock-service:stocking
    ports:
      - "8080:8080"
    environment:
      PROFILE: "prod"
      DATABASESERVER_PORT: "5432"
