version: '2'
services:
  database:
    extends:
      file: ../common/docker-compose.yml
      service: database
    environment:
      POSTGRES_USER: "postgres_dev"
      POSTGRES_PASSWORD: "p0stgr@s_dev"
      POSTGRES_DB:       "stockdb_dev"
  stockservice:
    image: skayvanfar/stock-service
    ports:
      - "8081:8081"
    environment:
      PROFILE: "dev"
      DATABASESERVER_PORT: "5432"
